version: 0.0.{build}

branches:
  only:
    - master

skip_tags: true

max_jobs: 1

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input
  - ps: $env:customBuildVersion = "$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_BUILD_NUMBER"
  - ps: $env:customNugetVersion = $env:APPVEYOR_BUILD_VERSION
  - ps: Update-AppveyorBuild -Version $env:customBuildVersion

clone_folder: c:\projects\janiceiq.metaengine.core

clone_depth: 5

matrix:
  fast_finish: true

platform: x64

configuration: Release

before_build:
  - nuget restore

build:
  parallel: true
  project: JaniceIq.MetaEngine.Core.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: normal

after_build:
  - ps: nuget pack .\JaniceIq.MetaEngine.Core.nuspec -Version $env:customNugetVersion

artifacts:
  - path: '**\JaniceIq.MetaEngine.Core*.nupkg'
    name: NuGet Deployment Package
    type: NuGetPackage

deploy:
  - provider: NuGet
    name: nuget_release
    api_key:
      secure: $env:NUGET_DEPLOYMENT_SECRET
    skip_symbols: false
    artifact: /^JaniceIq.MetaEngine.Core.*\.nupkg$/
    on:
      branch: master