version: 0.0.{build}-{branch}

branches:
  only:
    - master

skip_tags: true

max_jobs: 1

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input
  - ps: $env:customBuildVersion = if ($env:APPVEYOR_REPO_TAG -eq $True) { "$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_BUILD_NUMBER" } else { "$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_BUILD_NUMBER-$env:APPVEYOR_REPO_BRANCH" }
  - ps: $env:customNugetVersion = if ($env:APPVEYOR_REPO_TAG -eq $True) { "$env:APPVEYOR_BUILD_VERSION" } else { "$env:APPVEYOR_BUILD_VERSION-pre" }
  - ps: Update-AppveyorBuild -Version $env:customBuildVersion

clone_folder: c:\projects\janiceiq.metaengine.core

clone_depth: 5

matrix:
  fast_finish: true

platform: x64

configuration: Release

before_build:
  - nuget restore

build:
  parallel: true
  project: JaniceIq.MetaEngine.Core.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal

after_build:
  - ps: nuget pack .\SharpCaster\SharpCaster.nuspec -Version $env:customNugetVersion

artifacts:
  - path: '**\JaniceIq.MetaEngine.Core*.nupkg'
    name: Nuget
